server:
  port: 8765

spring:
  application:
    name: api-gateway
#  security:
#    oauth2:
#      resourceserver:
#        jwt:
#          issuer-uri: http://localhost:8181/realms/spring-boot-microservices-realm

  #Spring Cloud Gateway routes . . .
  cloud:
    gateway:
      mvc:
        routes:
          - id: order-service
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/api/order/**

          - id: product-service
            uri: lb://PRODUCT-SERVICE
            predicates:
              - Path=/api/product/**
#            filters:
#              - StripPrefix=1

          - id: inventory-service
            uri: lb://INVENTORY-SERVICE
            predicates:
              - Path=/api/inventory/**

          - id: auth-service
            uri: lb://AUTH-SERVICE
            predicates:
              - Path=/auth/**

#          - id: discovery-server
#            uri: lb://DISCOVERY-SERVER
#            predicates:
#              - Path=/discovery/**
#            filters:
#              - path=/


          - id: discovery-server
            uri: http://${DISCOVERY_SERVER:localhost}:8761
            predicates:
              - Path=/eureka/web
            filters:
              - SetPath=/

          - id: discovery-server-static-content
            uri: http://${DISCOVERY_SERVER:localhost}:8761
            predicates:
              - Path=/eureka/**

logging:
  level:
    root: info
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: info
    org.springframework.cloud.gateway: trace