# This is GLOBAL configuration file for every microservice in the system.

spring:
  application:
    name: config-server

# Zipkin Configs . . .
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans

# Eureka server configurations . . .
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
      
#logging:
#  level:
#    org:
#      springframework: DEBUG
#      hibernate: DEBUG
#      com:
#        order_service: DEBUG
