# This is GLOBAL configuration file for every microservice in the system.

spring:
  application:
    name: config-server

# Zipkin Configs . . .
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN:localhost}:9411/api/v2/spans
  # endpoints:
  #   web:
  #     exposure:
  #       include: "*"

# Eureka server configurations . . .
eureka:
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_SERVER:localhost}:8761/eureka/
      
#logging:
#  level:
#    org:
#      springframework: DEBUG
#      hibernate: DEBUG
#      com:
#        order_service: DEBUG
